/*
Network as Code

Manipulate network conditions via simplified REST calls

API version: 2
Contact: todd.levi@nokia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datarepository

import (
	"encoding/json"
)

// SubscriberId struct for SubscriberId
type SubscriberId struct {
	Id string `json:"id" yaml:"id" bson:"id" mapstructure:"Id"`
}

// NewSubscriberId instantiates a new SubscriberId object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubscriberId(id string) *SubscriberId {
	this := SubscriberId{}
	this.Id = id
	return &this
}

// NewSubscriberIdWithDefaults instantiates a new SubscriberId object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubscriberIdWithDefaults() *SubscriberId {
	this := SubscriberId{}
	return &this
}

// GetId returns the Id field value
func (o *SubscriberId) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SubscriberId) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SubscriberId) SetId(v string) {
	o.Id = v
}

func (o SubscriberId) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableSubscriberId struct {
	value *SubscriberId
	isSet bool
}

func (v NullableSubscriberId) Get() *SubscriberId {
	return v.value
}

func (v *NullableSubscriberId) Set(val *SubscriberId) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriberId) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriberId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriberId(val *SubscriberId) *NullableSubscriberId {
	return &NullableSubscriberId{value: val, isSet: true}
}

func (v NullableSubscriberId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriberId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


