/*
 * Ndscf_DataRepository
 *
 * Ndscf Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	datarepository "github.com/cnshackthon/dscf/go"
)

func main() {
	log.Printf("Server started")

	LocationApiService := datarepository.NewLocationApiService()
	LocationApiController := datarepository.NewLocationApiController(LocationApiService)

	RecordCRUDApiService := datarepository.NewRecordCRUDApiService()
	RecordCRUDApiController := datarepository.NewRecordCRUDApiController(RecordCRUDApiService)

	SubscriberApiService := datarepository.NewSubscriberApiService()
	SubscriberApiController := datarepository.NewSubscriberApiController(SubscriberApiService)

	UeIdCRUDApiService := datarepository.NewUeIdCRUDApiService()
	UeIdCRUDApiController := datarepository.NewUeIdCRUDApiController(UeIdCRUDApiService)

	router := datarepository.NewRouter(LocationApiController, RecordCRUDApiController, SubscriberApiController, UeIdCRUDApiController)

	log.Fatal(http.ListenAndServe("127.0.0.1:8081", router))
}
