/*
 * Ndscf_DataRepository
 *
 * Ndscf Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datarepository

import (
	"context"
	"net/http"
)



// LocationApiRouter defines the required methods for binding the api requests to a responses for the LocationApi
// The LocationApiRouter implementation should parse necessary information from the http request,
// pass the data to a LocationApiServicer to perform the required actions, then write the service results to the http response.
type LocationApiRouter interface { 
	GetSubIdLocation(http.ResponseWriter, *http.Request)
}
// RecordCRUDApiRouter defines the required methods for binding the api requests to a responses for the RecordCRUDApi
// The RecordCRUDApiRouter implementation should parse necessary information from the http request,
// pass the data to a RecordCRUDApiServicer to perform the required actions, then write the service results to the http response.
type RecordCRUDApiRouter interface { 
	DeleteCorrelation(http.ResponseWriter, *http.Request)
}
// SubscriberApiRouter defines the required methods for binding the api requests to a responses for the SubscriberApi
// The SubscriberApiRouter implementation should parse necessary information from the http request,
// pass the data to a SubscriberApiServicer to perform the required actions, then write the service results to the http response.
type SubscriberApiRouter interface { 
	GetSubIdLocation(http.ResponseWriter, *http.Request)
}
// UeIdCRUDApiRouter defines the required methods for binding the api requests to a responses for the UeIdCRUDApi
// The UeIdCRUDApiRouter implementation should parse necessary information from the http request,
// pass the data to a UeIdCRUDApiServicer to perform the required actions, then write the service results to the http response.
type UeIdCRUDApiRouter interface { 
	CreateOrModifyCorrelation(http.ResponseWriter, *http.Request)
}


// LocationApiServicer defines the api actions for the LocationApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type LocationApiServicer interface { 
	GetSubIdLocation(context.Context, string) (ImplResponse, error)
}


// RecordCRUDApiServicer defines the api actions for the RecordCRUDApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type RecordCRUDApiServicer interface { 
	DeleteCorrelation(context.Context, string, []string) (ImplResponse, error)
}


// SubscriberApiServicer defines the api actions for the SubscriberApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type SubscriberApiServicer interface { 
	GetSubIdLocation(context.Context, string) (ImplResponse, error)
}


// UeIdCRUDApiServicer defines the api actions for the UeIdCRUDApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type UeIdCRUDApiServicer interface { 
	CreateOrModifyCorrelation(context.Context, string, SubIds) (ImplResponse, error)
}
