/*
 * Ndscf_DataRepository
 *
 * Ndscf Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datarepository

import (
	"context"
	"net/http"
	"errors"
)

// RecordCRUDApiService is a service that implements the logic for the RecordCRUDApiServicer
// This service should implement the business logic for every endpoint for the RecordCRUDApi API.
// Include any external packages or services that will be required by this service.
type RecordCRUDApiService struct {
}

// NewRecordCRUDApiService creates a default api service
func NewRecordCRUDApiService() RecordCRUDApiServicer {
	return &RecordCRUDApiService{}
}

// DeleteCorrelation - Delete a Record with an user provided RecordId
func (s *RecordCRUDApiService) DeleteCorrelation(ctx context.Context, ueId string, subIds []string) (ImplResponse, error) {
	// TODO - update DeleteCorrelation with the required logic for this service method.
	// Add api_record_crud_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	//return Response(204, nil),nil

	//TODO: Uncomment the next line to return response Response(0, {}) or use other options such as http.Ok ...
	//return Response(0, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteCorrelation method not implemented")
}
