/*
 * Ndscf_DataRepository
 *
 * Ndscf Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datarepository

import (
	"context"
	"net/http"
	"errors"
)

// UeIdCRUDApiService is a service that implements the logic for the UeIdCRUDApiServicer
// This service should implement the business logic for every endpoint for the UeIdCRUDApi API.
// Include any external packages or services that will be required by this service.
type UeIdCRUDApiService struct {
}

// NewUeIdCRUDApiService creates a default api service
func NewUeIdCRUDApiService() UeIdCRUDApiServicer {
	return &UeIdCRUDApiService{}
}

// CreateOrModifyCorrelation - Create/Modify correlation between ueId and subIDs
func (s *UeIdCRUDApiService) CreateOrModifyCorrelation(ctx context.Context, ueId string, subIds SubIds) (ImplResponse, error) {
	// TODO - update CreateOrModifyCorrelation with the required logic for this service method.
	// Add api_ue_id_crud_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	//return Response(204, nil),nil

	//TODO: Uncomment the next line to return response Response(0, {}) or use other options such as http.Ok ...
	//return Response(0, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreateOrModifyCorrelation method not implemented")
}
